title: "Michael Mathu Kariuki"
email: "michael.mathu63@gmail.com"
description: >-
  Cyber Security Portfolio: Projects, Certifications, Write-ups, and Contact.
baseurl: "" # Leave this empty when using yourusername.github.io
url: "https://michael-mathu.github.io"
repository: "Michael-Mathu/Michael-Mathu.github.io"

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-include-cache

# Site Author
author:
  name: "Michael Mathu Kariuki"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Cybersecurity learner | Multimedia creator | AI enthusiast"
  location: "Nairobi, Kenya"
  email: "michael.mathu63@gmail.com"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/michael-mathu-074226192"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/Michael-Mathu"


# Theme settings
minimal_mistakes_skin: "default"
locale: "en-GB"
breadcrumbs: true
search: true
search_full_content: true

# Footer
footer:
  links:
    - label: "LinkedIn"
      url: "https://linkedin.com/in/michael-mathu-074226192"
    - label: "GitHub"
      url: "https://github.com/Michael-Mathu"

# Navigation setup
include: ["_pages"]
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
